### ISSUE TITLE
¡Hola!

### ISSUE THREAD

**Issue by NopAngel** [Eyvarjgc/PapelCrepeWeb#1]
Porfavor arreglar el tema de las Cards, las Cards nisiquiera las tocas, y te lo detecta como un Hover. Otra cosa, en el Texto de "Precios" porfavor arregarle una tipografía normal o una que se entienda, o simplemente ponerle un poco más de Ancho. Gracias y feliz día

**Comment by Eyvarjgc** [comment]
> Porfavor arreglar el tema de las Cards, las Cards nisiquiera las tocas, y te lo detecta como un Hover. Otra cosa, en el Texto de "Precios" porfavor arregarle una tipografía normal o una que se entienda, o simplemente ponerle un poco más de Ancho. Gracias y feliz día

Gracias por el feedback, el efecto hover en las Cards el cliente lo solicito de esa forma. Tomare en cuenta tu recomendacion del texto en 'Precios'  :3
